# -*- coding: utf-8 -*-
# Copyright (C) 2013-Today  Carlos Eduardo Vercelino - CLVsol
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).

{
    'name': 'Lab Test (customizations for CLVhealth-JCAFB Solution)',
    'summary': 'Lab Test Module customizations for CLVhealth-JCAFB Solution.',
    'version': '16.0.7.1',
    'author': 'Carlos Eduardo Vercelino - CLVsol',
    'category': 'CLVsol Solutions',
    'license': 'AGPL-3',
    'website': 'https://github.com/CLVsol',
    'depends': [
        'clv_lab_test',
        'clv_file_system',
        'clv_employee',
        'clv_set',
        'clv_base_jcafb',
        'clv_survey',
    ],
    'data': [
        'security/ir.model.access.csv',
        'views/lab_test_type_view.xml',
        'wizard/lab_test_result_approve_view.xml',
        'views/lab_test_result_view.xml',
        'views/lab_test_result_code_view.xml',
        'wizard/lab_test_result_export_xls_view.xml',
        'wizard/lab_test_result_report_export_xls_view.xml',
        'views/file_system_view.xml',
        'views/global_settings_view.xml',
        'views/lab_test_export_xls_param_view.xml',
        'views/lab_test_export_xls_param_pattern_view.xml',
        'views/lab_test_menu_view.xml',
        'data/lab_test_result_seq.xml',
        'data/file_system.xml',
        'data/global_settings.xml',
        'data/set_element.xml',
        'data/lab_test_export_xls_param_pattern.xml',
        'wizard/lab_test_result_receive_view.xml',
        'wizard/lab_test_result_associate_to_set_view.xml',
    ],
    'demo': [],
    'test': [],
    'init_xml': [],
    'test': [],
    'update_xml': [],
    'installable': True,
    'application': False,
    'active': False,
    'css': [],
}
