# -*- coding: utf-8 -*-
# Copyright (C) 2013-Today  Carlos Eduardo Vercelino - CLVsol
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).

{
    'name': 'Residence',
    'summary': 'Residence Module used by CLVsol Solutions.',
    'version': '14.0.5.0',
    'author': 'Carlos Eduardo Vercelino - CLVsol',
    'category': 'CLVsol Solutions',
    'license': 'AGPL-3',
    'website': 'https://github.com/CLVsol',
    'depends': [
        'clv_base',
        'clv_partner_entity',
        'clv_global_log',
        'clv_global_tag',
        # 'clv_address',
        'clv_employee',
    ],
    'data': [
        'security/residence_security.xml',
        'security/ir.model.access.csv',
        'data/global_settings.xml',
        'data/default_value.xml',
        'views/residence_view.xml',
        'views/residence_log_view.xml',
        'views/residence_category_view.xml',
        'views/residence_category_log_view.xml',
        'views/residence_marker_view.xml',
        'views/residence_tag_view.xml',
        'views/res_partner_view.xml',
        'views/global_tag_view.xml',
        'views/residence_name_view.xml',
        'views/global_settings_view.xml',
        # 'views/address_view.xml',
        'views/phase_view.xml',
        'views/residence_reg_state_view.xml',
        'views/residence_state_view.xml',
        'views/employee_view.xml',
        'wizard/residence_mass_edit_view.xml',
        'wizard/residence_contact_information_updt_view.xml',
        'views/residence_menu_view.xml',
        'data/global_log_client.xml',
    ],
    'demo': [],
    'test': [],
    'init_xml': [],
    'test': [],
    'update_xml': [],
    'installable': True,
    'application': False,
    'active': False,
    'css': [],
}
