# -*- coding: utf-8 -*-
# Copyright (C) 2013-Today  Carlos Eduardo Vercelino - CLVsol
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).

{
    'name': 'Family (Off)',
    'summary': 'Family (Off) Module used by CLVsol Solutions.',
    'version': '4.0.0',
    'author': 'Carlos Eduardo Vercelino - CLVsol',
    'category': 'Generic Modules/Others',
    'license': 'AGPL-3',
    'website': 'https://github.com/CLVsol',
    'depends': [
        'clv_base',
        'clv_global_log',
        'clv_partner_entity',
        'clv_global_tag',
        'clv_address',
        'clv_address_off',
        'clv_family',
    ],
    'data': [
        'security/family_off_security.xml',
        'security/ir.model.access.csv',
        'views/family_off_view.xml',
        'views/family_off_log_view.xml',
        'views/family_off_category_view.xml',
        'views/family_off_marker_view.xml',
        'views/res_partner_view.xml',
        'views/global_tag_view.xml',
        'views/family_off_name_view.xml',
        'views/family_view.xml',
        'views/address_view.xml',
        'views/address_off_view.xml',
        'wizard/family_off_mass_edit_view.xml',
        'wizard/family_associate_to_family_off_view.xml',
        'wizard/family_off_associate_to_address_off_view.xml',
    ],
    'demo': [],
    'test': [],
    'init_xml': [],
    'test': [],
    'update_xml': [],
    'installable': True,
    'application': False,
    'active': False,
    'css': [],
}
