# -*- coding: utf-8 -*-
# Copyright (C) 2013-Today  Carlos Eduardo Vercelino - CLVsol
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).

{
    'name': 'Patient (Rec)',
    'summary': 'Patient (Rec) Module used by CLVsol Solutions.',
    'version': '16.0.7.0',
    'author': 'Carlos Eduardo Vercelino - CLVsol',
    'category': 'CLVsol Solutions',
    'license': 'AGPL-3',
    'website': 'https://github.com/CLVsol',
    'images': [],
    'depends': [
        'clv_base',
        'clv_partner_entity',
        'clv_global_tag',
        'clv_patient',
    ],
    'data': [
        'security/patient_rec_security.xml',
        'security/ir.model.access.csv',
        'views/patient_rec_view.xml',
        'views/patient_rec_marker_view.xml',
        'views/patient_rec_category_view.xml',
        'views/res_partner_view.xml',
        'views/global_tag_view.xml',
        'views/address_name_view.xml',
        'views/patient_view.xml',
        'views/phase_view.xml',
        'views/patient_rec_reg_state_view.xml',
        'views/patient_rec_state_view.xml',
        'wizard/patient_rec_mass_edit_view.xml',
        'views/patient_rec_menu_view.xml',
    ],
    'demo': [],
    'test': [],
    'init_xml': [],
    'test': [],
    'update_xml': [],
    'installable': True,
    'application': False,
    'active': False,
    'css': [],
}
